version: '3.9'

services:
  db:
    image: postgres:14.7
    restart: always
    environment:
      POSTGRES_USER: delivery
      POSTGRES_PASSWORD: password
      POSTGRES_DB: deliveryApp
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - delivery-network
  web:
    image: parceldeliveryapp
    restart: unless-stopped
    environment:
      APP_NAME: "parceldeliveryapp"
      SPRING_PROFILES_ACTIVE: "test"
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - delivery-network

volumes:
  db_data:

networks:
  delivery-network:
